config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get 'home/index'

  scope module: 'users' do
    devise_for :users, skip: :registrations
  end

  resources :users

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :user

  validates :first_name,
    :last_name,
    :city,
    :state,
    :pincode,
    presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable,
    :lockable

  has_one :address, dependent: :destroy

  accepts_nested_attributes_for :address

  validates :email, presence: true
  validates :password, presence: true, length: { in: 6..20 }
  validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # Sets the flash message with :key, using I18n. By default you are able
  # to set up your messages using specific resource scope, and if no message is
  # found we look to the default scope. Set the "now" options key to a true
  # value to populate the flash.now hash in lieu of the default flash hash (so
  # the flash message will be available to the current action instead of the
  # next action).
  # Example (i18n locale file):
  #
  #   en:
  #     users:
  #       create:
  #         signed_up: #flash message
  #
  # Please refer to en.yml locale file to check what messages are
  # available.
  def set_flash_message(key, kind, options = {})
    message = find_message(kind, options)
    if options[:now]
      flash.now[key] = message if message.present?
    else
      flash[key] = message if message.present?
    end
  end

  # Get message for given
  def find_message(kind, options = {})
    options[:resource_name] ||= controller_name
    options[:action_name] ||= action_name
    I18n.t("#{options[:resource_name]}.#{options[:action_name]}.#{kind}", options)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @user = User.new
    @user.build_address
    respond_to do |format|
      format.html
    end
  end

  # TODO - Modify below mthod after integration of Email confirmatin module
  # of devise
  def create
    @user = User.new(user_params)
    if @user.save
      set_flash_message :notice, :signed_up
      redirect_to new_user_session_path
    else
      set_flash_message :error, :not_able_to_signed_up
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :email, 
        :password, 
        :password_confirmation, 
        address_attributes: [
          :first_name, 
          :middle_name, 
          :last_name, 
          :city, 
          :state, 
          :pincode
        ]
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Home
%p home page will be coming soon...
%p Contents  links are coming soon......
%p Website will be fully desgined for geeks, learn algorithms  go...

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NitinEdu
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div
      - if flash.present?
        = flash.each do |key, value|
          = value
    %div
      - if user_signed_in?
        = link_to 'Sign out', destroy_user_session_path, method: :delete
    = yield

app/views/users/_form.html.haml
= puts "----controller_name=#{controller_name}---#{action_name}---"
= form_for @user do |f|
  %div
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true, autocomplete: "email"
  %div
    = f.label :password
    %br/
    = f.password_field :password, autocomplete: "off"
  %div
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation, autocomplete: "off"
  %div
    = f.fields_for :address do |add|
      %div
        = add.label :first_name
        %br/
        = add.text_field :first_name
      %div
        = add.label :middle_name
        %br/
        = add.text_field :middle_name
      %div
        = add.label :last_name
        %br/
        = add.text_field :last_name
      %div
        = add.label :city
        %br/
        = add.text_field :city
      %div
        = add.label :state
        %br/
        = add.text_field :state
      %div
        = add.label :pincode
        %br/
        = add.text_field :pincode
  %div
    = f.submit "Sign up"
= link_to 'Log In', new_user_session_path

app/views/users/edit.html.haml
%h2 Edit your details
= render partial: 'form'

app/views/users/new.html.haml
%h2 Sign up
= render partial: 'form'

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_user_session_path
  %br/
= link_to "Sign up", new_user_path
%br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_user_password_path
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_user_unlock_path
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/